# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zgomot}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Troy Stribling"]
  s.date = %q{2010-11-25}
  s.default_executable = %q{zgomot}
  s.email = %q{troy.stribling@gmail.com}
  s.executables = ["zgomot"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/zgomot",
    "examples/arp_chords.rb",
    "examples/full_scale_notes.rb",
    "examples/inv_chords.rb",
    "examples/modes_notes.rb",
    "examples/notes.rb",
    "examples/percs.rb",
    "examples/percs_multi.rb",
    "examples/phase_notes.rb",
    "examples/prog_chords.rb",
    "examples/prog_chords_multi_vel_length.rb",
    "examples/prog_chords_rest.rb",
    "examples/prog_notes.rb",
    "examples/prog_notes_multi_vel_length.rb",
    "examples/prog_notes_rest.rb",
    "examples/progressive_modes.rb",
    "examples/reverse_chords.rb",
    "examples/scale_chords.rb",
    "examples/scale_notes.rb",
    "examples/scales_notes.rb",
    "examples/simple_chords.rb",
    "examples/simple_markov.rb",
    "examples/simple_notes.rb",
    "examples/simple_notes_length.rb",
    "examples/simple_notes_velocity.rb",
    "examples/zgomot.yml",
    "lib/zgomot.rb",
    "lib/zgomot/boot.rb",
    "lib/zgomot/comp.rb",
    "lib/zgomot/comp/chord.rb",
    "lib/zgomot/comp/markov.rb",
    "lib/zgomot/comp/mode.rb",
    "lib/zgomot/comp/note.rb",
    "lib/zgomot/comp/pattern.rb",
    "lib/zgomot/comp/perc.rb",
    "lib/zgomot/comp/permutation.rb",
    "lib/zgomot/comp/pitch_class.rb",
    "lib/zgomot/comp/progression.rb",
    "lib/zgomot/comp/scale.rb",
    "lib/zgomot/config.rb",
    "lib/zgomot/main.rb",
    "lib/zgomot/midi.rb",
    "lib/zgomot/midi/channel.rb",
    "lib/zgomot/midi/clock.rb",
    "lib/zgomot/midi/dispatcher.rb",
    "lib/zgomot/midi/interface.rb",
    "lib/zgomot/midi/note.rb",
    "lib/zgomot/midi/stream.rb",
    "lib/zgomot/patches.rb",
    "lib/zgomot/patches/object.rb",
    "lib/zgomot/patches/time.rb",
    "lib/zlive.rb",
    "zgomot.gemspec"
  ]
  s.homepage = %q{http://github.com/troystribling/zgomot}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{zgomot is a simple DSL for writting MIDI music.}
  s.test_files = [
    "examples/arp_chords.rb",
    "examples/full_scale_notes.rb",
    "examples/inv_chords.rb",
    "examples/modes_notes.rb",
    "examples/notes.rb",
    "examples/percs.rb",
    "examples/percs_multi.rb",
    "examples/phase_notes.rb",
    "examples/prog_chords.rb",
    "examples/prog_chords_multi_vel_length.rb",
    "examples/prog_chords_rest.rb",
    "examples/prog_notes.rb",
    "examples/prog_notes_multi_vel_length.rb",
    "examples/prog_notes_rest.rb",
    "examples/progressive_modes.rb",
    "examples/reverse_chords.rb",
    "examples/scale_chords.rb",
    "examples/scale_notes.rb",
    "examples/scales_notes.rb",
    "examples/simple_chords.rb",
    "examples/simple_markov.rb",
    "examples/simple_notes.rb",
    "examples/simple_notes_length.rb",
    "examples/simple_notes_velocity.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0.8.3"])
      s.add_runtime_dependency(%q<midiator>, [">= 0.3.3"])
    else
      s.add_dependency(%q<rake>, [">= 0.8.3"])
      s.add_dependency(%q<midiator>, [">= 0.3.3"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0.8.3"])
    s.add_dependency(%q<midiator>, [">= 0.3.3"])
  end
end

